/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ballpark Predict API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Create a new game room
 */
export const createGameBodyHostNameMax = 30;

export const createGameBodyAwayTeamMax = 30;

export const createGameBodyHomeTeamMax = 30;

export const createGameBodyVenueMax = 60;

export const CreateGameBody = zod.object({
  hostName: zod.string().min(1).max(createGameBodyHostNameMax),
  awayTeam: zod.string().min(1).max(createGameBodyAwayTeamMax),
  homeTeam: zod.string().min(1).max(createGameBodyHomeTeamMax),
  venue: zod.string().max(createGameBodyVenueMax).optional(),
  mlbGamePk: zod
    .number()
    .nullish()
    .describe("Optional link to a real MLB game (StatsAPI gamePk)"),
});

/**
 * @summary Get a game by its room code
 */
export const GetGameByCodeParams = zod.object({
  code: zod.coerce.string(),
});

export const GetGameByCodeResponse = zod.object({
  game: zod.object({
    id: zod.string(),
    code: zod.string(),
    awayTeam: zod.string(),
    homeTeam: zod.string(),
    venue: zod.string().nullish(),
    status: zod.enum(["lobby", "live", "final"]),
    hostPlayerId: zod.string(),
    mlbGamePk: zod.number().nullish(),
    mlbDetailedState: zod.string().nullish(),
    mlbAwayScore: zod.number().nullish(),
    mlbHomeScore: zod.number().nullish(),
    mlbCurrentInning: zod.number().nullish(),
    mlbCurrentHalf: zod.string().nullish(),
    createdAt: zod.coerce.date(),
  }),
  players: zod.array(
    zod.object({
      id: zod.string(),
      gameId: zod.string(),
      name: zod.string(),
      avatar: zod.string(),
      isHost: zod.boolean(),
      totalScore: zod.number(),
      joinedAt: zod.coerce.date(),
    }),
  ),
});

/**
 * @summary Join a game as a player
 */
export const JoinGameParams = zod.object({
  code: zod.coerce.string(),
});

export const joinGameBodyNameMax = 20;

export const JoinGameBody = zod.object({
  name: zod.string().min(1).max(joinGameBodyNameMax),
  avatar: zod.string(),
});

export const JoinGameResponse = zod.object({
  id: zod.string(),
  gameId: zod.string(),
  name: zod.string(),
  avatar: zod.string(),
  isHost: zod.boolean(),
  totalScore: zod.number(),
  joinedAt: zod.coerce.date(),
});

/**
 * @summary Get current leaderboard for a game
 */
export const GetLeaderboardParams = zod.object({
  code: zod.coerce.string(),
});

export const GetLeaderboardResponseItem = zod.object({
  playerId: zod.string(),
  name: zod.string(),
  avatar: zod.string(),
  totalScore: zod.number(),
  correctPicks: zod.number(),
  totalPicks: zod.number(),
  isHost: zod.boolean(),
});
export const GetLeaderboardResponse = zod.array(GetLeaderboardResponseItem);

/**
 * @summary List at-bats for a game (newest first)
 */
export const ListAtBatsParams = zod.object({
  code: zod.coerce.string(),
});

export const listAtBatsResponseInningMax = 12;

export const ListAtBatsResponseItem = zod.object({
  id: zod.string(),
  gameId: zod.string(),
  batterName: zod.string(),
  team: zod.string(),
  inning: zod.number().min(1).max(listAtBatsResponseInningMax),
  half: zod.enum(["top", "bottom"]),
  status: zod.enum(["open", "resolved"]),
  actualOutcome: zod
    .enum([
      "single",
      "double",
      "triple",
      "home_run",
      "out",
      "walk",
      "strikeout",
    ])
    .nullish(),
  createdAt: zod.coerce.date(),
  resolvedAt: zod.coerce.date().nullish(),
});
export const ListAtBatsResponse = zod.array(ListAtBatsResponseItem);

/**
 * @summary Host opens a new at-bat for predictions
 */
export const CreateAtBatParams = zod.object({
  code: zod.coerce.string(),
});

export const createAtBatBodyBatterNameMax = 40;

export const createAtBatBodyTeamMax = 30;

export const createAtBatBodyInningMax = 12;

export const CreateAtBatBody = zod.object({
  batterName: zod.string().min(1).max(createAtBatBodyBatterNameMax),
  team: zod.string().min(1).max(createAtBatBodyTeamMax),
  inning: zod.number().min(1).max(createAtBatBodyInningMax),
  half: zod.enum(["top", "bottom"]),
});

/**
 * @summary Get the active at-bat awaiting an outcome
 */
export const GetCurrentAtBatParams = zod.object({
  code: zod.coerce.string(),
});

export const getCurrentAtBatResponseAtBatOneInningMax = 12;

export const GetCurrentAtBatResponse = zod.object({
  atBat: zod
    .object({
      id: zod.string(),
      gameId: zod.string(),
      batterName: zod.string(),
      team: zod.string(),
      inning: zod.number().min(1).max(getCurrentAtBatResponseAtBatOneInningMax),
      half: zod.enum(["top", "bottom"]),
      status: zod.enum(["open", "resolved"]),
      actualOutcome: zod
        .enum([
          "single",
          "double",
          "triple",
          "home_run",
          "out",
          "walk",
          "strikeout",
        ])
        .nullish(),
      createdAt: zod.coerce.date(),
      resolvedAt: zod.coerce.date().nullish(),
    })
    .nullable(),
});

/**
 * @summary Host records the actual outcome of an at-bat
 */
export const ResolveAtBatParams = zod.object({
  atBatId: zod.coerce.string(),
});

export const ResolveAtBatBody = zod.object({
  outcome: zod.enum([
    "single",
    "double",
    "triple",
    "home_run",
    "out",
    "walk",
    "strikeout",
  ]),
});

export const resolveAtBatResponseAtBatInningMax = 12;

export const ResolveAtBatResponse = zod.object({
  atBat: zod.object({
    id: zod.string(),
    gameId: zod.string(),
    batterName: zod.string(),
    team: zod.string(),
    inning: zod.number().min(1).max(resolveAtBatResponseAtBatInningMax),
    half: zod.enum(["top", "bottom"]),
    status: zod.enum(["open", "resolved"]),
    actualOutcome: zod
      .enum([
        "single",
        "double",
        "triple",
        "home_run",
        "out",
        "walk",
        "strikeout",
      ])
      .nullish(),
    createdAt: zod.coerce.date(),
    resolvedAt: zod.coerce.date().nullish(),
  }),
  awarded: zod.array(
    zod.object({
      playerId: zod.string(),
      playerName: zod.string(),
      points: zod.number(),
      correct: zod.boolean(),
    }),
  ),
});

/**
 * @summary Submit a player's prediction for an at-bat
 */
export const PredictAtBatParams = zod.object({
  atBatId: zod.coerce.string(),
});

export const PredictAtBatBody = zod.object({
  playerId: zod.string(),
  prediction: zod.enum([
    "single",
    "double",
    "triple",
    "home_run",
    "out",
    "walk",
    "strikeout",
  ]),
});

export const PredictAtBatResponse = zod.object({
  id: zod.string(),
  atBatId: zod.string(),
  playerId: zod.string(),
  prediction: zod.enum([
    "single",
    "double",
    "triple",
    "home_run",
    "out",
    "walk",
    "strikeout",
  ]),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Get aggregate count of predictions per outcome for an at-bat
 */
export const GetAtBatPredictionSummaryParams = zod.object({
  atBatId: zod.coerce.string(),
});

export const GetAtBatPredictionSummaryResponseItem = zod.object({
  outcome: zod.enum([
    "single",
    "double",
    "triple",
    "home_run",
    "out",
    "walk",
    "strikeout",
  ]),
  count: zod.number(),
});
export const GetAtBatPredictionSummaryResponse = zod.array(
  GetAtBatPredictionSummaryResponseItem,
);

/**
 * @summary Get a player's pre-game picks (winner, HR hitters, walks, K's)
 */
export const GetPlayerPicksParams = zod.object({
  code: zod.coerce.string(),
  playerId: zod.coerce.string(),
});

export const GetPlayerPicksResponse = zod.object({
  playerId: zod.string(),
  gameId: zod.string(),
  winnerTeam: zod.string().nullish(),
  awayFinalScore: zod.number().nullish(),
  homeFinalScore: zod.number().nullish(),
  hrHitters: zod.array(zod.string()),
  totalWalks: zod.number().nullish(),
  totalStrikeouts: zod.number().nullish(),
});

/**
 * @summary Save / update a player's pre-game picks
 */
export const SavePlayerPicksParams = zod.object({
  code: zod.coerce.string(),
  playerId: zod.coerce.string(),
});

export const savePlayerPicksBodyAwayFinalScoreMin = 0;
export const savePlayerPicksBodyAwayFinalScoreMax = 30;

export const savePlayerPicksBodyHomeFinalScoreMin = 0;
export const savePlayerPicksBodyHomeFinalScoreMax = 30;

export const savePlayerPicksBodyHrHittersItemMax = 40;

export const savePlayerPicksBodyHrHittersMax = 6;

export const savePlayerPicksBodyTotalWalksMin = 0;
export const savePlayerPicksBodyTotalWalksMax = 30;

export const savePlayerPicksBodyTotalStrikeoutsMin = 0;
export const savePlayerPicksBodyTotalStrikeoutsMax = 30;

export const SavePlayerPicksBody = zod.object({
  winnerTeam: zod.string().nullish(),
  awayFinalScore: zod
    .number()
    .min(savePlayerPicksBodyAwayFinalScoreMin)
    .max(savePlayerPicksBodyAwayFinalScoreMax)
    .nullish(),
  homeFinalScore: zod
    .number()
    .min(savePlayerPicksBodyHomeFinalScoreMin)
    .max(savePlayerPicksBodyHomeFinalScoreMax)
    .nullish(),
  hrHitters: zod
    .array(zod.string().max(savePlayerPicksBodyHrHittersItemMax))
    .max(savePlayerPicksBodyHrHittersMax)
    .optional(),
  totalWalks: zod
    .number()
    .min(savePlayerPicksBodyTotalWalksMin)
    .max(savePlayerPicksBodyTotalWalksMax)
    .nullish(),
  totalStrikeouts: zod
    .number()
    .min(savePlayerPicksBodyTotalStrikeoutsMin)
    .max(savePlayerPicksBodyTotalStrikeoutsMax)
    .nullish(),
});

export const SavePlayerPicksResponse = zod.object({
  playerId: zod.string(),
  gameId: zod.string(),
  winnerTeam: zod.string().nullish(),
  awayFinalScore: zod.number().nullish(),
  homeFinalScore: zod.number().nullish(),
  hrHitters: zod.array(zod.string()),
  totalWalks: zod.number().nullish(),
  totalStrikeouts: zod.number().nullish(),
});

/**
 * @summary Get a player's per-inning run guesses
 */
export const GetInningGuessesParams = zod.object({
  code: zod.coerce.string(),
  playerId: zod.coerce.string(),
});

export const getInningGuessesResponseInningMax = 12;

export const getInningGuessesResponseRunsMin = 0;
export const getInningGuessesResponseRunsMax = 15;

export const GetInningGuessesResponseItem = zod.object({
  playerId: zod.string(),
  gameId: zod.string(),
  inning: zod.number().min(1).max(getInningGuessesResponseInningMax),
  half: zod.enum(["top", "bottom"]),
  runs: zod
    .number()
    .min(getInningGuessesResponseRunsMin)
    .max(getInningGuessesResponseRunsMax),
});
export const GetInningGuessesResponse = zod.array(GetInningGuessesResponseItem);

/**
 * @summary Save a single inning run guess
 */
export const SaveInningGuessParams = zod.object({
  code: zod.coerce.string(),
  playerId: zod.coerce.string(),
});

export const saveInningGuessBodyInningMax = 12;

export const saveInningGuessBodyRunsMin = 0;
export const saveInningGuessBodyRunsMax = 15;

export const SaveInningGuessBody = zod.object({
  inning: zod.number().min(1).max(saveInningGuessBodyInningMax),
  half: zod.enum(["top", "bottom"]),
  runs: zod
    .number()
    .min(saveInningGuessBodyRunsMin)
    .max(saveInningGuessBodyRunsMax),
});

export const saveInningGuessResponseInningMax = 12;

export const saveInningGuessResponseRunsMin = 0;
export const saveInningGuessResponseRunsMax = 15;

export const SaveInningGuessResponse = zod.object({
  playerId: zod.string(),
  gameId: zod.string(),
  inning: zod.number().min(1).max(saveInningGuessResponseInningMax),
  half: zod.enum(["top", "bottom"]),
  runs: zod
    .number()
    .min(saveInningGuessResponseRunsMin)
    .max(saveInningGuessResponseRunsMax),
});

/**
 * @summary List MLB games for a given date (defaults to today)
 */
export const GetMlbScheduleQueryParams = zod.object({
  date: zod.coerce.string().optional(),
});

export const GetMlbScheduleResponseItem = zod.object({
  gamePk: zod.number(),
  awayTeam: zod.string(),
  homeTeam: zod.string(),
  venue: zod.string(),
  gameDate: zod.coerce.date(),
  detailedState: zod.string(),
  abstractGameState: zod.string(),
  awayScore: zod.number().nullish(),
  homeScore: zod.number().nullish(),
});
export const GetMlbScheduleResponse = zod.array(GetMlbScheduleResponseItem);

/**
 * @summary Find-or-create the shared room for an MLB game and join it
 */
export const JoinMlbGameParams = zod.object({
  gamePk: zod.coerce.number(),
});

export const joinMlbGameBodyNameMax = 30;

export const joinMlbGameBodyAvatarMax = 8;

export const JoinMlbGameBody = zod.object({
  name: zod.string().min(1).max(joinMlbGameBodyNameMax),
  avatar: zod.string().max(joinMlbGameBodyAvatarMax),
});

export const JoinMlbGameResponse = zod.object({
  game: zod.object({
    id: zod.string(),
    code: zod.string(),
    awayTeam: zod.string(),
    homeTeam: zod.string(),
    venue: zod.string().nullish(),
    status: zod.enum(["lobby", "live", "final"]),
    hostPlayerId: zod.string(),
    mlbGamePk: zod.number().nullish(),
    mlbDetailedState: zod.string().nullish(),
    mlbAwayScore: zod.number().nullish(),
    mlbHomeScore: zod.number().nullish(),
    mlbCurrentInning: zod.number().nullish(),
    mlbCurrentHalf: zod.string().nullish(),
    createdAt: zod.coerce.date(),
  }),
  player: zod.object({
    id: zod.string(),
    gameId: zod.string(),
    name: zod.string(),
    avatar: zod.string(),
    isHost: zod.boolean(),
    totalScore: zod.number(),
    joinedAt: zod.coerce.date(),
  }),
});

/**
 * @summary Roster (batters) for both teams of an MLB game, for HR-pick selection
 */
export const GetMlbRosterParams = zod.object({
  gamePk: zod.coerce.number(),
});

export const GetMlbRosterResponse = zod.object({
  awayTeam: zod.string(),
  homeTeam: zod.string(),
  away: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      position: zod.string(),
      jerseyNumber: zod.string().nullish(),
    }),
  ),
  home: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      position: zod.string(),
      jerseyNumber: zod.string().nullish(),
    }),
  ),
});

/**
 * @summary Sync a linked game with its real MLB live feed
 */
export const SyncGameWithMlbParams = zod.object({
  code: zod.coerce.string(),
});

export const SyncGameWithMlbResponse = zod.object({
  linked: zod.boolean(),
  message: zod.string().nullish(),
  resolvedCount: zod.number(),
  openedCurrent: zod.boolean(),
  gameStatus: zod.enum(["lobby", "live", "final"]).optional(),
});

/**
 * @summary Recent at-bat outcomes and points awarded
 */
export const GetRecentActivityParams = zod.object({
  code: zod.coerce.string(),
});

export const GetRecentActivityResponseItem = zod.object({
  id: zod.string(),
  atBatId: zod.string(),
  batterName: zod.string(),
  inning: zod.number(),
  half: zod.enum(["top", "bottom"]),
  outcome: zod.enum([
    "single",
    "double",
    "triple",
    "home_run",
    "out",
    "walk",
    "strikeout",
  ]),
  awardedCount: zod.number(),
  topScorer: zod
    .object({
      playerId: zod.string(),
      name: zod.string(),
      points: zod.number(),
    })
    .nullable(),
  createdAt: zod.coerce.date(),
});
export const GetRecentActivityResponse = zod.array(
  GetRecentActivityResponseItem,
);
