/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ballpark Predict API
 * OpenAPI spec version: 0.1.0
 */
import type { Half } from "./half";

export interface CreateAtBatInput {
  /**
   * @minLength 1
   * @maxLength 40
   */
  batterName: string;
  /**
   * @minLength 1
   * @maxLength 30
   */
  team: string;
  /**
   * @minimum 1
   * @maximum 12
   */
  inning: number;
  half: Half;
}
