/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ballpark Predict API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateGameInput {
  /**
   * @minLength 1
   * @maxLength 30
   */
  hostName: string;
  /**
   * @minLength 1
   * @maxLength 30
   */
  awayTeam: string;
  /**
   * @minLength 1
   * @maxLength 30
   */
  homeTeam: string;
  /** @maxLength 60 */
  venue?: string;
  /** Optional link to a real MLB game (StatsAPI gamePk) */
  mlbGamePk?: number | null;
}
