/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ballpark Predict API
 * OpenAPI spec version: 0.1.0
 */
import type { GameStatus } from "./gameStatus";

export interface Game {
  id: string;
  code: string;
  awayTeam: string;
  homeTeam: string;
  venue?: string | null;
  status: GameStatus;
  hostPlayerId: string;
  mlbGamePk?: number | null;
  mlbDetailedState?: string | null;
  mlbAwayScore?: number | null;
  mlbHomeScore?: number | null;
  mlbCurrentInning?: number | null;
  mlbCurrentHalf?: string | null;
  createdAt: Date;
}
