/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ballpark Predict API
 * OpenAPI spec version: 0.1.0
 */

export type GameStatus = (typeof GameStatus)[keyof typeof GameStatus];

export const GameStatus = {
  lobby: "lobby",
  live: "live",
  final: "final",
} as const;
