/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ballpark Predict API
 * OpenAPI spec version: 0.1.0
 */

export type Half = (typeof Half)[keyof typeof Half];

export const Half = {
  top: "top",
  bottom: "bottom",
} as const;
