/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ballpark Predict API
 * OpenAPI spec version: 0.1.0
 */
import type { Half } from "./half";

export interface InningGuess {
  playerId: string;
  gameId: string;
  /**
   * @minimum 1
   * @maximum 12
   */
  inning: number;
  half: Half;
  /**
   * @minimum 0
   * @maximum 15
   */
  runs: number;
}
