/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ballpark Predict API
 * OpenAPI spec version: 0.1.0
 */
import type { Game } from "./game";
import type { Player } from "./player";

export interface JoinMlbGameResult {
  game: Game;
  player: Player;
}
