/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ballpark Predict API
 * OpenAPI spec version: 0.1.0
 */

export interface JoinMlbGameInput {
  /**
   * @minLength 1
   * @maxLength 30
   */
  name: string;
  /** @maxLength 8 */
  avatar: string;
}
