/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ballpark Predict API
 * OpenAPI spec version: 0.1.0
 */

export interface LeaderboardEntry {
  playerId: string;
  name: string;
  avatar: string;
  totalScore: number;
  correctPicks: number;
  totalPicks: number;
  isHost: boolean;
}
