/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ballpark Predict API
 * OpenAPI spec version: 0.1.0
 */
import type { MlbRosterPlayer } from "./mlbRosterPlayer";

export interface MlbRoster {
  awayTeam: string;
  homeTeam: string;
  away: MlbRosterPlayer[];
  home: MlbRosterPlayer[];
}
