/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ballpark Predict API
 * OpenAPI spec version: 0.1.0
 */
import type { GameStatus } from "./gameStatus";

export interface MlbSyncResult {
  linked: boolean;
  message?: string | null;
  resolvedCount: number;
  openedCurrent: boolean;
  gameStatus?: GameStatus;
}
