/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ballpark Predict API
 * OpenAPI spec version: 0.1.0
 */

export type PitchOutcome = (typeof PitchOutcome)[keyof typeof PitchOutcome];

export const PitchOutcome = {
  single: "single",
  double: "double",
  triple: "triple",
  home_run: "home_run",
  out: "out",
  walk: "walk",
  strikeout: "strikeout",
} as const;
