/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ballpark Predict API
 * OpenAPI spec version: 0.1.0
 */

export interface Player {
  id: string;
  gameId: string;
  name: string;
  avatar: string;
  isHost: boolean;
  totalScore: number;
  joinedAt: Date;
}
