/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ballpark Predict API
 * OpenAPI spec version: 0.1.0
 */

export interface SavePlayerPicksInput {
  winnerTeam?: string | null;
  /**
   * @minimum 0
   * @maximum 30
   */
  awayFinalScore?: number | null;
  /**
   * @minimum 0
   * @maximum 30
   */
  homeFinalScore?: number | null;
  /** @maxItems 6 */
  hrHitters?: string[];
  /**
   * @minimum 0
   * @maximum 30
   */
  totalWalks?: number | null;
  /**
   * @minimum 0
   * @maximum 30
   */
  totalStrikeouts?: number | null;
}
